### ISSUE TITLE
Add /careers page like gatsbyjs.com/careers

### ISSUE THREAD

**Issue by ElijahLynn** [agilesix/AgileSix.com#13]
-- Let's table this until we get a revamped site design. We've incorporated looking at careers in that story. (https://github.com/agilesix/agilesix.com/issues/22)

Saw this tweet by @gatsbyjs about their [/careers](https://www.gatsbyjs.com/careers/) page and thought it would be nice to add something like this to our site. 

https://twitter.com/gatsbyjs/status/1215398218944610310
![image](https://user-images.githubusercontent.com/1504756/72112686-2eb0c580-32f3-11ea-9ef6-71d58672ae2c.png)

cc @JQuaggles @bderfer68 @robrasmussen1970

**Comment by DanielMiller-agile6** [comment]
That is a really nice careers page!  Seems warm, friendly and super informative.  I'd love to help out if we decide to do something similar :)

**Comment by ElijahLynn** [comment]
There is a bit of a /careers type page on https://agile6.com/team right now, under the "Join Our Team" section at the bottom.

**Comment by JQuaggles** [comment]
@ElijahLynn I'd like to add a separate /Careers page with a link in the top nav. Might not be like you are displaying above, but would like to take it out of the /team page and have it stand by itself.
How long would something like that take?

**Comment by JQuaggles** [comment]
Gotcha, thanks @ElijahLynn - appreciate it

**Comment by JQuaggles** [comment]
Moving this up to have an interim Careers page on the current site. There is no current intent in the near future to redo the website again. If I need to create a new ticket for this for just a new page in the current site, I can do that.
